"use client";

import Link from "next/link";
import { useState } from "react";
import { Copy, Check, ArrowLeft } from "lucide-react";
import { motion } from "framer-motion";
import { AnimatedSection } from "@/components/AnimatedSection";

const paper = {
  title: "Representing Egocentric Directions with Torso-Applied Vibrotactile Stimuli",
  authors: [
    { name: "Junwoo Kim", affil: "1" },
    { name: "Jaejun Park", affil: "1" },
    { name: "Chaeyong Park", affil: "2", url: "https://chaeyongpark.github.io/" },
    { name: "Junseok Park", affil: "3" },
    { name: "Seungmoon Choi", affil: "1" , url: "https://choism.postech.ac.kr/"},
  ],
  affiliations: [
    { id: "1", name: "POSTECH" },
    { id: "2", name: "Korea University" },
    { id: "3", name: "ETRI" },
  ],
  venue: "IEEE Transactions on Haptics",
  venueShort: "IEEE Trans. Haptics",
  year: 2026,
  doi: "https://doi.org/10.1109/TOH.2026.3667214",
  abstract: `This paper investigates egocentric directional perception of azimuth and elevation in response to torso-based vibrotactile stimuli for both stimulus identification and direction association under a common experimental framework. We conducted four perceptual experiments that examined the two tasks for azimuth and elevation, using real vibrations and illusory stimuli generated by the funneling illusion. The results demonstrated that adding illusory stimuli effectively conveyed directional information with fewer tactors than using only real stimuli. Azimuth perception revealed a lateral bias, whereas elevation perception exhibited a downward bias on the dorsal torso, particularly in the upper back. However, both azimuth and elevation cues were generally consistent across vertical and horizontal torso locations. Additionally, we estimated regression models for both egocentric angles and showed that perceived directions could be estimated from actual stimulus positions. Correlation analysis revealed a weak relationship between azimuth and elevation perceptual errors, suggesting that these dimensions are processed with near-independence. Across all findings, azimuth cues proved to be more effective than elevation cues in conveying directional information. This study provides a comprehensive understanding of egocentric directions and offers practical insights for the design of torso-based vibrotactile displays.`,
};

const contributions = [
  "First unified experimental framework examining both azimuth and elevation perception for stimulus identification and direction association on the full torso",
  "Demonstrated that illusory stimuli (funneling illusion) effectively convey directional information with fewer physical tactors, doubling spatial resolution from 8 to 16 azimuths",
  "Revealed that the upper torso (chest and solar plexus) outperforms the waist for azimuth cueing, while the abdomen and upper back show reduced elevation identification accuracy",
  "Established regression models that accurately map physical stimulus positions to perceived egocentric directions — enabling data-driven haptic vest design",
  "Showed that azimuth and elevation perception errors are nearly independent (r = 0.08), suggesting minimal cross-axis interference in torso-based directional cueing",
];

const experiments = [
  {
    id: "Exp. I-1",
    title: "Azimuth Identification",
    participants: 12,
    desc: "Participants identified vibrotactile stimuli placed around the torso at three vertical levels (TOP, MID, BTM). REL sub-experiment used 8 real stimuli; R+I added 8 illusory stimuli for 16 total azimuths.",
    findings: "97.7% (REL, 8 dirs) · 77.8% (R+I, 16 dirs)",
    color: "teal",
  },
  {
    id: "Exp. I-2",
    title: "Elevation Identification",
    participants: 12,
    desc: "Participants identified vibrotactile stimuli placed vertically on the torso at two horizontal levels (MID and LFT). Upper back and abdominal regions showed notably lower accuracy.",
    findings: "96.9% (REL) · 75.5% (R+I)",
    color: "coral",
  },
  {
    id: "Exp. II-1",
    title: "Azimuth Association",
    participants: 12,
    desc: "Participants freely associated vibrotactile stimuli with egocentric azimuth angles using a touchscreen dial. Regression models were built from the collected data.",
    findings: "R²adj = 0.993 · RMSE = 8.37°",
    color: "teal",
  },
  {
    id: "Exp. II-2",
    title: "Elevation Association",
    participants: 12,
    desc: "Participants indicated perceived elevation for each torso stimulus. Downward bias observed on the dorsal torso; regression captured nonlinear mapping from actual to perceived elevation.",
    findings: "R²adj = 0.972 · RMSE = 15.77°",
    color: "coral",
  },
];

const findings = [
  { title: "Lateral bias in azimuth", desc: "Stimuli at intercardinal positions (~45°, 135°) were systematically perceived ~9.4° toward the lateral sides, attributed to the elliptical torso cross-section." },
  { title: "Downward bias in elevation", desc: "Dorsal torso stimuli — especially the upper back — were consistently associated with lower perceived elevations than ventral stimuli at the same height." },
  { title: "Upper torso advantage", desc: "Stimuli at the chest (TOP) and solar plexus (MID) allowed significantly higher azimuth identification accuracy than the waist (BTM)." },
  { title: "Illusory stimuli double resolution", desc: "Combining 8 real and 8 illusory stimuli increased effective azimuths from 8 to 16 directions (22.5° resolution) with only ~20% accuracy drop." },
  { title: "Near-independent dimensions", desc: "Pearson's r = 0.08 between azimuth and elevation MAEs confirms that these two directional dimensions are processed with near-independence." },
  { title: "Consistent across torso regions", desc: "Both azimuth and elevation cues showed consistent perceptual patterns across the full torso, validating haptic vest designs that use multiple belt positions." },
];

const colorClass: Record<string, { card: string; dot: string; text: string; badge: string }> = {
  teal:  { card: "bg-teal-50 border-teal-200",  dot: "bg-teal-500",  text: "text-teal-700",  badge: "bg-teal-100 text-teal-700" },
  coral: { card: "bg-coral-50 border-coral-200", dot: "bg-coral-500", text: "text-coral-700", badge: "bg-coral-100 text-coral-700" },
};

const bibtex = `@article{Kim2026:representing,
  author={Kim, Junwoo and Park, Jaejun and Park, Chaeyong and Park, Junseok and Choi, Seungmoon},
  journal={IEEE Transactions on Haptics},
  title={Representing Egocentric Directions With Torso-Applied Vibrotactile Stimuli},
  year={2026},
  volume={},
  number={},
  pages={1-13},
  keywords={Azimuth;Torso;Vibrations;Motors;Haptic interfaces;Accuracy;Belts;Artificial intelligence;Reviews;Abdomen;Egocentric Direction;Azimuth;Elevation;Vibrotactile Stimuli;Torso;Funneling Illusion},
  doi={10.1109/TOH.2026.3667214}}`;

const smHeightMap: Record<string, string> = {
  "h-56": "sm:h-56", "h-64": "sm:h-64", "h-72": "sm:h-72", "h-80": "sm:h-80", "h-96": "sm:h-96",
};
function FitImage({ src, alt, caption, h = "h-64" }: { src: string; alt: string; caption?: string; h?: string }) {
  const [err, setErr] = useState(false);
  const smH = smHeightMap[h] ?? "sm:h-64";
  return (
    <div className="flex flex-col items-center w-full">
      {!err ? (
        // eslint-disable-next-line @next/next/no-img-element
        <img
          src={src}
          alt={alt}
          className={`w-full h-auto ${smH} sm:w-auto rounded-xl border border-slate-200`}
          onError={() => setErr(true)}
        />
      ) : (
        <div className={`w-full ${smH} sm:w-48 rounded-xl bg-slate-100 border-2 border-dashed border-slate-200 flex items-center justify-center`}>
          <p className="text-xs text-slate-400 text-center px-2">Add: {src.split("/").pop()}</p>
        </div>
      )}
      {caption && <p className="text-sm text-slate-400 text-center mt-2 italic">{caption}</p>}
    </div>
  );
}

function CopyBibtex() {
  const [copied, setCopied] = useState(false);
  return (
    <button
      onClick={() => { navigator.clipboard.writeText(bibtex); setCopied(true); setTimeout(() => setCopied(false), 2000); }}
      className="inline-flex items-center gap-1.5 px-3 py-1.5 rounded-lg bg-slate-100 hover:bg-teal-50 hover:text-teal-600 text-slate-500 text-xs font-semibold transition-colors"
    >
      {copied ? <><Check size={13} />Copied!</> : <><Copy size={13} />Copy BibTeX</>}
    </button>
  );
}

export default function EgocentricDirectionPage() {
  return (
    <div className="bg-white min-h-screen">

      {/* Back */}
      <div className="container-main pt-8 pb-0">
        <Link href="/publications" className="inline-flex items-center gap-2 text-sm font-medium text-slate-400 hover:text-teal-600 transition-colors">
          <ArrowLeft size={15} /> Publications
        </Link>
      </div>

      {/* Hero */}
      <section className="container-main py-10 sm:py-14">
        <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.6 }}>
          <div className="flex flex-wrap gap-2 mb-5">
            <span className="badge badge-teal text-sm px-3 py-1">{paper.venueShort} &middot; {paper.year}</span>
          </div>

          <h1 className="text-3xl sm:text-4xl lg:text-5xl font-extrabold text-slate-900 leading-tight mb-6 max-w-4xl">
            {paper.title}
          </h1>

          <div className="mb-2 flex flex-wrap gap-x-4 gap-y-1">
            {paper.authors.map((a) => (
              <span key={a.name} className="text-base text-slate-700 font-medium">
                {a.url ? (
                  <a href={a.url} target="_blank" rel="noopener noreferrer" className="underline decoration-teal-500 decoration-2 underline-offset-2 hover:decoration-teal-700">
                    {a.name}
                  </a>
                ) : a.name}
                <sup className="text-slate-400 text-xs ml-0.5">{a.affil}</sup>
              </span>
            ))}
          </div>

          <div className="mb-8 flex flex-wrap gap-x-4 gap-y-0.5">
            {paper.affiliations.map((a) => (
              <span key={a.id} className="text-sm text-slate-400">
                <sup className="mr-0.5">{a.id}</sup>{a.name}
              </span>
            ))}
          </div>

          {paper.doi && (
            <a href={paper.doi} target="_blank" rel="noopener noreferrer"
              className="inline-flex items-center gap-2 px-4 py-2 bg-teal-600 hover:bg-teal-700 text-white text-sm font-semibold rounded-lg transition-colors">
              View Paper (DOI)
            </a>
          )}
        </motion.div>
      </section>

      {/* Teaser — Fig 1 */}
      <section className="bg-slate-50/70 py-14">
        <div className="container-main">
          <AnimatedSection>
            <FitImage
              src="/images/pub_pages/egocentric-direction/fig1.png"
              alt="General definitions of azimuth and elevation representing egocentric directions and the four experiments"
              caption="Fig. 1. Azimuth and elevation define egocentric directions (a). Torso-based tactile direction cueing involves stimulus identification (b) and direction association (c), studied across four experiments."
              h="h-72"
            />
          </AnimatedSection>
        </div>
      </section>

      {/* Abstract */}
      <section className="py-14">
        <div className="container-main">
          <AnimatedSection>
            <h2 className="text-2xl font-extrabold text-slate-900 mb-5 flex items-center gap-3">
              <span className="w-8 h-1 bg-teal-500 rounded-full inline-block" />
              Abstract
            </h2>
            <p className="text-base text-slate-600 leading-relaxed">{paper.abstract}</p>
          </AnimatedSection>
        </div>
      </section>

      {/* Key Contributions */}
      <section className="bg-slate-50/70 py-14">
        <div className="container-main">
          <AnimatedSection>
            <h2 className="text-2xl font-extrabold text-slate-900 mb-8 flex items-center gap-3">
              <span className="w-8 h-1 bg-teal-500 rounded-full inline-block" />
              Key Contributions
            </h2>
            <ul className="space-y-4">
              {contributions.map((c, i) => (
                <li key={i} className="flex gap-4">
                  <span className="shrink-0 w-7 h-7 rounded-full bg-teal-500 text-white text-sm font-bold flex items-center justify-center mt-0.5">
                    {i + 1}
                  </span>
                  <p className="text-base text-slate-600 leading-relaxed">{c}</p>
                </li>
              ))}
            </ul>
          </AnimatedSection>
        </div>
      </section>

      {/* Apparatus — Fig 3 */}
      <section className="py-14">
        <div className="container-main">
          <AnimatedSection>
            <h2 className="text-2xl font-extrabold text-slate-900 mb-3 flex items-center gap-3">
              <span className="w-8 h-1 bg-teal-500 rounded-full inline-block" />
              Apparatus
            </h2>
            <p className="text-base text-slate-500 mb-8">
              A commercial haptic vest (bHaptics TactSuit X40) was customized to precisely control vibration positions on the torso. Vibration motors were removed from the inner vest and placed into 3D-printed housings mounted on three adjustable belt straps. Each belt contained eight motors arranged at cardinal and intercardinal directions. An additional motor was affixed to each shoulder, yielding 26 stimulation points in total. Real stimuli (10 G, 61 Hz) and illusory stimuli (funneling illusion, 7 G each) were delivered to represent azimuths and elevations.
            </p>
          </AnimatedSection>

          <div className="grid grid-cols-2 sm:grid-cols-4 gap-4 mb-8">
            {[
              { value: "26", label: "Vibration Points", sub: "8×3 torso + 2 shoulder" },
              { value: "4", label: "Experiments", sub: "2 identification + 2 association" },
              { value: "12/exp", label: "Participants", sub: "per sub-experiment" },
              { value: "61 Hz", label: "Stimulus Frequency", sub: "10 G amplitude" },
            ].map((s) => (
              <AnimatedSection key={s.label}>
                <div className="card p-4 text-center">
                  <p className="text-2xl font-extrabold text-teal-600 mb-0.5">{s.value}</p>
                  <p className="text-sm font-semibold text-slate-700">{s.label}</p>
                  <p className="text-xs text-slate-400">{s.sub}</p>
                </div>
              </AnimatedSection>
            ))}
          </div>

          <AnimatedSection>
            <FitImage
              src="/images/pub_pages/egocentric-direction/fig3.png"
              alt="Customized haptic suit: overall structure, fitting vibration motors, and final look"
              caption="Fig. 3. The customized haptic suit: (a) overall structure showing vibration motors and straps, (b) fitting motors to the torso, and (c) final wearable configuration."
              h="h-80"
            />
          </AnimatedSection>
        </div>
      </section>

      {/* Identification Experiments — Fig 5 + Fig 6 */}
      <section className="bg-slate-50/70 py-14">
        <div className="container-main">
          <AnimatedSection>
            <h2 className="text-2xl font-extrabold text-slate-900 mb-3 flex items-center gap-3">
              <span className="w-8 h-1 bg-coral-500 rounded-full inline-block" />
              Exp. I: Azimuth &amp; Elevation Identification
            </h2>
            <p className="text-base text-slate-500 mb-8">
              Two experiments measured how accurately participants identified vibrotactile cues representing azimuth (Exp. I-1, 8 or 16 directions) and elevation (Exp. I-2, 6–13 levels). Both compared real-only (REL) and real+illusory (R+I) stimulus conditions.
            </p>
          </AnimatedSection>

          <div className="grid grid-cols-1 sm:grid-cols-2 gap-5 mb-10">
            {experiments.slice(0, 2).map((exp, i) => {
              const c = colorClass[exp.color];
              return (
                <AnimatedSection key={exp.id} delay={i * 0.07}>
                  <div className={`card p-6 border h-full ${c.card}`}>
                    <div className="flex items-center gap-3 mb-3">
                      <span className={`w-3 h-3 rounded-full ${c.dot}`} />
                      <span className={`text-xs font-bold px-2 py-0.5 rounded ${c.badge}`}>{exp.id}</span>
                      <span className={`font-bold text-sm ${c.text}`}>{exp.title}</span>
                    </div>
                    <p className="text-xs text-slate-400 mb-2">N = {exp.participants} participants</p>
                    <p className="text-sm text-slate-600 leading-relaxed mb-3">{exp.desc}</p>
                    <div className={`rounded-lg px-3 py-2 text-xs font-semibold ${c.badge}`}>
                      {exp.findings}
                    </div>
                  </div>
                </AnimatedSection>
              );
            })}
          </div>

          <AnimatedSection>
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-6 items-start">
              <FitImage
                src="/images/pub_pages/egocentric-direction/fig5.png"
                alt="Azimuth identification accuracies across torso positions"
                caption="Fig. 5. Azimuth identification accuracies with standard errors (Exp. I-1). Orange areas indicate stimuli with significantly lower accuracy."
                h="h-80"
              />
              <FitImage
                src="/images/pub_pages/egocentric-direction/fig6.png"
                alt="Elevation identification accuracies across torso positions"
                caption="Fig. 6. Elevation identification accuracies with standard errors (Exp. I-2). Blue and orange areas mark regions of reduced performance."
                h="h-80"
              />
            </div>
          </AnimatedSection>
        </div>
      </section>

      {/* Association Experiments — Fig 9 + Fig 12 */}
      <section className="py-14">
        <div className="container-main">
          <AnimatedSection>
            <h2 className="text-2xl font-extrabold text-slate-900 mb-3 flex items-center gap-3">
              <span className="w-8 h-1 bg-gold-500 rounded-full inline-block" />
              Exp. II: Direction Association &amp; Regression Models
            </h2>
            <p className="text-base text-slate-500 mb-8">
              Two experiments measured how participants naturally associate vibrotactile stimuli with egocentric directions — azimuth (Exp. II-1) and elevation (Exp. II-2) — without explicit training constraints. Fourier regression models were fit to characterize the physical-to-perceived angle mapping.
            </p>
          </AnimatedSection>

          <div className="grid grid-cols-1 sm:grid-cols-2 gap-5 mb-10">
            {experiments.slice(2).map((exp, i) => {
              const c = colorClass[exp.color];
              return (
                <AnimatedSection key={exp.id} delay={i * 0.07}>
                  <div className={`card p-6 border h-full ${c.card}`}>
                    <div className="flex items-center gap-3 mb-3">
                      <span className={`w-3 h-3 rounded-full ${c.dot}`} />
                      <span className={`text-xs font-bold px-2 py-0.5 rounded ${c.badge}`}>{exp.id}</span>
                      <span className={`font-bold text-sm ${c.text}`}>{exp.title}</span>
                    </div>
                    <p className="text-xs text-slate-400 mb-2">N = {exp.participants} participants</p>
                    <p className="text-sm text-slate-600 leading-relaxed mb-3">{exp.desc}</p>
                    <div className={`rounded-lg px-3 py-2 text-xs font-semibold ${c.badge}`}>
                      {exp.findings}
                    </div>
                  </div>
                </AnimatedSection>
              );
            })}
          </div>

          <AnimatedSection>
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-6 items-start">
              <FitImage
                src="/images/pub_pages/egocentric-direction/fig9.png"
                alt="Means and standard errors of associated azimuths across three vertical levels"
                caption="Fig. 9. Associated azimuths across three torso heights (TOP, MID, BTM) and overall. Stimuli show clear lateral bias for intercardinal positions."
                h="h-96"
              />
              <FitImage
                src="/images/pub_pages/egocentric-direction/fig12.png"
                alt="Means and standard errors of associated elevations across horizontal levels"
                caption="Fig. 12. Associated elevations across LFT, MID, and RHT torso positions. Orange shading denotes stimuli with non-significant pairwise differences."
                h="h-96"
              />
            </div>
          </AnimatedSection>
        </div>
      </section>

      {/* Key Findings */}
      <section className="bg-slate-50/70 py-14">
        <div className="container-main">
          <AnimatedSection>
            <h2 className="text-2xl font-extrabold text-slate-900 mb-3 flex items-center gap-3">
              <span className="w-8 h-1 bg-teal-500 rounded-full inline-block" />
              Key Findings &amp; Design Implications
            </h2>
            <p className="text-base text-slate-500 mb-8">
              Findings from all four experiments offer practical guidelines for designing torso-based vibrotactile directional displays.
            </p>
          </AnimatedSection>
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4">
            {findings.map((g, i) => (
              <AnimatedSection key={g.title} delay={i * 0.06}>
                <div className="card p-5 h-full">
                  <div className="flex items-start gap-3 mb-2">
                    <span className="shrink-0 w-6 h-6 rounded-full bg-teal-500 text-white text-xs font-bold flex items-center justify-center mt-0.5">
                      {i + 1}
                    </span>
                    <p className="font-bold text-slate-900 text-sm leading-snug">{g.title}</p>
                  </div>
                  <p className="text-sm text-slate-500 leading-relaxed pl-9">{g.desc}</p>
                </div>
              </AnimatedSection>
            ))}
          </div>
        </div>
      </section>

      {/* Citation */}
      <section className="py-14">
        <div className="container-main">
          <AnimatedSection>
            <div className="flex items-center justify-between mb-4 flex-wrap gap-3">
              <h2 className="text-2xl font-extrabold text-slate-900 flex items-center gap-3">
                <span className="w-8 h-1 bg-teal-500 rounded-full inline-block" />
                Citation
              </h2>
              <CopyBibtex />
            </div>
            <pre className="bg-slate-900 text-slate-100 text-sm rounded-xl p-5 overflow-x-auto leading-relaxed font-mono">
              {bibtex}
            </pre>
          </AnimatedSection>
        </div>
      </section>

      {/* Acknowledgment */}
      <div className="container-main py-8 text-center">
        <p className="text-sm text-slate-400">
          This work was supported by a grant 23ZS1200 from ETRI, a grant RS-2024-00437866 from the IITP, and a grant RS-2024-00451947 from the NRF of Korea.
        </p>
      </div>

    </div>
  );
}
